### ISSUE TITLE
last day seams to be wrong

### ISSUE THREAD

**Issue by pippopippo69** [mohabmes/pystocklib#1]
Hi,

great work!

I noticed that the last day seams to be wrong.. Data are ok but date is one day less.

could you check please?

**Comment by mohabmes** [comment]
Hi @pippopippo69 

**pystocklib** uses **yahoo finance** to fetch its data.

It seems like they've entered the same date for two different days accidentally, that is what caused this problem for the rest of the month.

I have checked a lot of stock ticker to confirm, it seems fine & doesn't have the same problem.
Hope they fix it soon.
